package functionid

type FunctionId string

// 列管所有domain service內的function,用於traceMap,function以f_開頭
const (
	ParseCreateGuestConnectTokenRequest FunctionId = "f_ParseCreateGuestConnectTokenRequest"
	GenConnectToken                     FunctionId = "f_GenConnectToken"
	ParseAuthConnectTokenRequest        FunctionId = "f_ParseAuthConnectTokenRequest"
	ParseConnectToken                   FunctionId = "f_ParseConnectToken"
	GetPlayerInfo                       FunctionId = "f_GetPlayerInfo"
	AddConnectToken2Db                  FunctionId = "f_AddConnectToken2Db"
	ParseUpdateTokenLocationRequest     FunctionId = "f_ParseUpdateTokenLocationRequest"
	UpdateTokenLocation                 FunctionId = "f_UpdateTokenLocation"
	IsConnectTokenAlive                 FunctionId = "f_IsConnectTokenAlive"
	ParseGetConnectTokenInfoRequest     FunctionId = "f_ParseGetConnectTokenInfoRequest"
	GetPlayerInfoCache                  FunctionId = "f_GetPlayerInfoCache"
	ParseGetConnectTokenAmountRequest   FunctionId = "f_ParseGetConnectTokenAmountRequest"
	ParseDelConnectTokenRequest         FunctionId = "f_ParseDelConnectTokenRequest"
	LogOutToken                         FunctionId = "f_LogOutToken"
	ParseGetSequenceNumberRequest       FunctionId = "f_ParseGetSequenceNumberRequest"
	GetGameSequenceNumber               FunctionId = "f_GetGameSequenceNumber"
	ParseGetSequenceNumbersRequest      FunctionId = "f_ParseGetSequenceNumbersRequest"
	GetGameSequenceNumbers              FunctionId = "f_GetGameSequenceNumbers"
	ParseRoundCheckRequest              FunctionId = "f_ParseRoundCheckRequest"
	GetRoundCheckList                   FunctionId = "f_GetRoundCheckList"
	ParseGameResultRequest              FunctionId = "f_ParseGameResultRequest"
	AddGameResultAndRollHistory         FunctionId = "f_AddGameResultAndRollHistory"
	RefreshWallet                       FunctionId = "f_RefreshWallet"
	ParseFinishGameResultRequest        FunctionId = "f_ParseFinishGameResultRequest"
	IsFinishGameResultConnectTokenAlive FunctionId = "f_IsFinishGameResultConnectTokenAlive"
	IsFinishGameResultConnectTokenError FunctionId = "f_IsFinishGameResultConnectTokenError"
	GetPlayerWallet                     FunctionId = "f_GetPlayerWallet"
	AddGameResult                       FunctionId = "f_AddGameResult"
	AddRollInHistory                    FunctionId = "f_AddRollInHistory"
	ParseAddGameLogRequest              FunctionId = "f_ParseAddGameLogRequest"
	IsBaseCheckError                    FunctionId = "f_IsBaseCheckError"
	IsConnectTokenError                 FunctionId = "f_IsConnectTokenError"
	Currency2ExchangeRate               FunctionId = "f_Currency2ExchangeRate"
	AddGameLog2Db                       FunctionId = "f_AddGameLog2Db"
	ParseOrderListRequest               FunctionId = "f_ParseOrderListRequest"
	GetGameLanguage                     FunctionId = "f_GetGameLanguage"
	GetReportUrl                        FunctionId = "f_GetReportUrl"
	ParseRollOutRequest                 FunctionId = "f_ParseRollOutRequest"
	AddRollOutHistory                   FunctionId = "f_AddRollOutHistory"
	ParseRollInRequest                  FunctionId = "f_ParseRollInRequest"
	HasRollOutHistory                   FunctionId = "f_HasRollOutHistory"
	ParseSettlementRequest              FunctionId = "f_ParseSettlementRequest"
	AddUnpayActivityRank                FunctionId = "f_AddUnpayActivityRank"
	ParseDistributionRequest            FunctionId = "f_ParseDistributionRequest"
	GetDistributionWallet               FunctionId = "f_GetDistributionWallet"
	HasUnpayActivityDistribution        FunctionId = "f_HasUnpayActivityDistribution"
	ActivityDistribution                FunctionId = "f_ActivityDistribution"
	ParseCurrencyListRequest            FunctionId = "f_ParseCurrencyListRequest"
	GetSupportCurrency                  FunctionId = "f_GetSupportCurrency"
	ParseDefaultError                   FunctionId = "f_ParseDefaultError"
	IsValid                             FunctionId = "f_IsValid"
	ValidateAccount                     FunctionId = "f_ValidateAccount"
	ReadHttpRequestBody                 FunctionId = "f_ReadHttpRequestBody"
	ParseJsonBody                       FunctionId = "f_ParseJsonBody"
	CallThirdApi                        FunctionId = "f_callThirdApi"
)
