package functionid

type FunctionId string

// 列管所有domain service內的function,用於traceMap,對應service所以特定編號
// *TODO 後續量比較多的話應該拉出一個function層重編為流水號
const (
	ParseCreateGuestConnectTokenRequest FunctionId = "FC1.0.0"
	GenConnectToken                     FunctionId = "FC1.0.1"
	ParseAuthConnectTokenRequest        FunctionId = "FC1.1.0"
	ParseConnectToken                   FunctionId = "FC1.1.1"
	GetPlayerInfo                       FunctionId = "FC1.1.2"
	AddConnectToken2Db                  FunctionId = "FC1.1.3"
	ParseUpdateTokenLocationRequest     FunctionId = "FC1.2.0"
	UpdateTokenLocation                 FunctionId = "FC1.2.1"
	IsConnectTokenAlive                 FunctionId = "FC1.2.2"
	ParseGetConnectTokenInfoRequest     FunctionId = "FC1.3.0"
	GetPlayerInfoCache                  FunctionId = "FC1.3.1"
	ParseGetConnectTokenAmountRequest   FunctionId = "FC1.4.0"
	ParseDelConnectTokenRequest         FunctionId = "FC1.5.0"
	LogOutToken                         FunctionId = "FC1.5.1"
	ParseGetSequenceNumberRequest       FunctionId = "FC2.1.0"
	GetGameSequenceNumber               FunctionId = "FC2.1.1"
	ParseGetSequenceNumbersRequest      FunctionId = "FC2.2.0"
	GetGameSequenceNumbers              FunctionId = "FC2.2.1"
	ParseRoundCheckRequest              FunctionId = "FC2.3.0"
	GetRoundCheckList                   FunctionId = "FC2.3.1"
	ParseGameResultRequest              FunctionId = "FC3.1.0"
	AddGameResultAndRollHistory         FunctionId = "FC3.1.1"
	RefreshWallet                       FunctionId = "FC3.1.2"
	ParseFinishGameResultRequest        FunctionId = "FC3.2.0"
	IsFinishGameResultConnectTokenAlive FunctionId = "FC3.2.1"
	IsFinishGameResultConnectTokenError FunctionId = "FC3.2.2"
	GetPlayerWallet                     FunctionId = "FC3.2.3"
	AddGameResult                       FunctionId = "FC3.2.4"
	AddRollInHistory                    FunctionId = "FC3.2.5"
	ParseAddGameLogRequest              FunctionId = "FC3.3.0"
	IsBaseCheckError                    FunctionId = "FC3.3.1"
	IsConnectTokenError                 FunctionId = "FC3.3.2"
	Currency2ExchangeRate               FunctionId = "FC3.3.3"
	AddGameLog2Db                       FunctionId = "FC3.3.4"
	ParseOrderListRequest               FunctionId = "FC4.1.0"
	GetGameLanguage                     FunctionId = "FC4.1.1"
	GetReportUrl                        FunctionId = "FC4.1.2"
	ParseRollOutRequest                 FunctionId = "FC5.1.0"
	AddRollOutHistory                   FunctionId = "FC5.1.1"
	ParseRollInRequest                  FunctionId = "FC5.2.0"
	HasRollOutHistory                   FunctionId = "FC5.2.1"
	ParseSettlementRequest              FunctionId = "FC6.1.0"
	AddUnpayActivityRank                FunctionId = "FC6.1.1"
	ParseDistributionRequest            FunctionId = "FC6.2.0"
	GetDistributionWallet               FunctionId = "FC6.2.1"
	HasUnpayActivityDistribution        FunctionId = "FC6.2.2"
	ActivityDistribution                FunctionId = "FC6.2.3"
	ParseCurrencyListRequest            FunctionId = "FC7.1.0"
	GetSupportCurrency                  FunctionId = "FC7.1.1"
	ParseDefaultError                   FunctionId = "FC0.0.0"
	IsValid                             FunctionId = "FC0.0.1"
	ValidateAccount                     FunctionId = "FC0.0.2"
	ReadHttpRequestBody                 FunctionId = "FC0.0.3"
	ParseJsonBody                       FunctionId = "FC0.0.4"
)
